### ISSUE TITLE
Parcel can't load GLSL shaders

### ISSUE THREAD

**Issue by 22mahmoud** [22mahmoud/Phaser.io-v3-Boilerplate#1]
When turn WEBGL_RENDERER variable to true phaser throw this error 

`
Uncaught Error: Failed to compile Vertex Shader:
ERROR: 0:1: '/' : syntax error
`

**Comment by RiCoTeRoX** [comment]
how you turn on and off that flag in parcel ? i want to do the same with PLUGIN_FBINSTANT.

thank in advanced
