### ISSUE TITLE
GitHub repository description typo

### ISSUE THREAD

**Issue by Flet** [22mahmoud/Phaser.io-v3-Boilerplate#3]
Thanks for putting this together, it looks really useful!

I noticed there is a typo in the repository description:
"🕹 Phaser.io v3 minimal Boilerplate w/ parceljs **blunder** ( ES6 )"

I assume you meant **bundler** instead of **blunder** (unless you're not a fan of parceljs hehe)

Thanks again for the boilerplate 👋

**Comment by 22mahmoud** [comment]
Hi @Flet Thanks,
I fixed it :smile:
